# Full reference at http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}

build_script:
- ps: if($env:APPVEYOR_REPO_BRANCH -ne "release"){C:\projects\publish-module\build.ps1 -build} else {C:\projects\publish-module\build.ps1 -build -publishToNuget}

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT

artifacts:
  - path: 'OutputRoot\**\*'

nuget:
  account_feed: true
  project_feed: true
