# Full reference at http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}
os: Visual Studio 2015 CTP

build_script:
- ps: .\appveyor.ps1

environment:
  NuGetApiKey:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT
  NuGetApiKeyStaging:
    secure: HFUEQanhaxHV/sRQYznQqg7LToxSGeIoSvrmyY29PJ1eDbXxUuYrEQ6MPAsZIQFT
  NuGetPrivateFeedUrl:
    secure: oVpjg1GHzihvdCcsXYFwhuB3qD6lWsCXLS7xWJJna21Fk8ouML8iGULZ87a+jLO8a2SkLB8zFyCNOiPzdQsMBA==

artifacts:
  - path: 'OutputRoot\**\*'

nuget:
  account_feed: true
  project_feed: true
