# Full reference at http://www.appveyor.com/docs/appveyor-yml

version: 1.0.{build}

build_script:
- ps: C:\projects\publish-module\build.ps1

artifacts:
  - path: 'OutputRoot\**\*'

nuget:
  account_feed: true
  project_feed: true